name = "FFTA"
uuid = "b86e33f2-c0db-4aa1-a6e0-ab43e668529e"
version = "0.3.0"
authors = ["Danny Sharp <dannys4@mit.edu> and contributors"]

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Aqua = "0.8"
DocStringExtensions = "0.9"
ExplicitImports = "1.12"
LinearAlgebra = "<0.0.1, 1"
MuladdMacro = "0.2"
Primes = "0.5"
Random = "<0.0.1, 1"
Reexport = "1"
Test = "<0.0.1, 1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ExplicitImports = "7d51a73a-1435-4ff3-83d9-f097790105c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ExplicitImports", "Test"]
